# Generated by Django 4.0.5 on 2022-06-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='meta_descripion',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='category',
            name='trending',
        ),
        migrations.AddField(
            model_name='product',
            name='new_arrival',
            field=models.BooleanField(default=False, help_text='0=default, 1=New Arrival'),
        ),
    ]
