# Generated by Django 4.0.5 on 2022-06-05 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_remove_category_meta_descripion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_type',
            new_name='slug',
        ),
    ]
